### ISSUE TITLE
Win7 Python 3.10 64bit issue: DLL load failed while importing _python_calamine

### ISSUE THREAD

**Issue by gufengaoyue** [dimastbk/python-calamine#83]
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import python_calamine
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import python_calamine
  File "C:\Python\lib\site-packages\python_calamine\__init__.py", line 2, in <module>
    from ._python_calamine import (
ImportError: DLL load failed while importing _python_calamine: The specified procedure could not be found

How to solve this problem? Thanks.

**Comment by Mrian707258535** [comment]
> 因为构建环境是windows server 2022

这个问题能解决吗

**Comment by gufengaoyue** [comment]
> > 因为构建环境是windows server 2022
> 
> 这个问题能解决吗

降级使用。0.2.0 这个版本可以。

**Comment by Mrian707258535** [comment]
> > > 因为构建环境是windows server 2022
> > 
> > 
> > 这个问题能解决吗
> 
> 降级使用。0.2.0 这个版本可以。

谢谢
